#!/usr/bin/env python2.7
from pb_git import cmds
import argparse
import os
import sys
import warnings

def get_default_mirrors_base():
    base = os.environ.get('PB_GIT_DEFAULT_MIRRORS_BASE', '/lustre/hpcprod/cdunn/git-mirrors-client/smrtanalysis/bioinformatics')
    # '' => do not use a mirror.
    if base and os.path.abspath(base) in os.path.abspath(os.getcwd()):
        warnings.warn('Cannot use base above cwd. Ignoring. ({!r} is in {!r})'.format(
            base, os.getcwd()))
        base = ''
    if base and not os.path.exists(base):
        warnings.warn('base does not exist. Ignoring. ({!r})'.format(
            base))
        base = ''
    return base

try:
    PB_GIT_DEFAULT_MIRRORS_BASE = get_default_mirrors_base()
except:
    # To be as robust as possible.
    PB_GIT_DEFAULT_MIRRORS_BASE = ''
#warnings.warn('base={!r}'.format(PB_GIT_DEFAULT_MIRRORS_BASE))


def main(argv):
    parser = argparse.ArgumentParser(
            formatter_class=argparse.ArgumentDefaultsHelpFormatter)
    cmds.init_argparse(parser)
    subparsers = parser.add_subparsers()

    p = subparsers.add_parser('checkout',
            help='Checkout all repos described by *.ini files, cloning and fetching as needed.',
            description='Checkout all repos described by *.ini files, cloning and fetching as needed. This will put the repos into "detached HEAD" state, just like git-submodules. Someday, we might add branch support.',
            #aliases=['co'],
            )
    p.add_argument('--mirrors',
            default=PB_GIT_DEFAULT_MIRRORS_BASE,
            help='Clone/fetch from the mirror first. Use this path, plus ext/pi etc. [default="%(default)s", which can be over-ridden via PB_GIT_DEFAULT_MIRRORS_BASE]',
            )
    p.set_defaults(func=cmds.checkout)

    p = subparsers.add_parser('prepare',
            help='Prepare to submit the current changes.',
            description='Prepare to submit the current changes, and `p4 edit` them. Work with intermediate *.ini.bak files. Users may run this command as often as they like. It is perfectly safe always. They must then run `p4 submit` themselves.',
            )
    p.add_argument('--no-verify',
            action='store_true',
            help='Do not perform the verify step.',
            )
    p.set_defaults(func=cmds.prepare)

    p = subparsers.add_parser('verify',
            help='Prove that the commit is actually available from a fresh checkout.',
            description='This will become faster when we have caching. Note that `prepare` can call this itself.',
            )
    p.set_defaults(func=cmds.verify)

    args = parser.parse_args(argv[1:])
    args.func(args)

main(sys.argv)
