#!/usr/bin/env python2.7
from pb_git import convert
import argparse
import sys

def main(argv):
    parser = argparse.ArgumentParser(
            description='Convert .gitmodules to this system.',
            formatter_class=argparse.ArgumentDefaultsHelpFormatter)
    parser.add_argument('-d', '--directory',
            default='.',
            help='Directory of submodules')
    parser.add_argument('-v', '--verbose',
            action='store_true')
    parser.set_defaults(func=convert.convert)

    args = parser.parse_args(argv[1:])
    args.func(args)

main(sys.argv)

