#!/usr/bin/env python2.7
from pb_git import cmds
import argparse
import sys

def main(argv):
    parser = argparse.ArgumentParser(
            formatter_class=argparse.ArgumentDefaultsHelpFormatter)
    cmds.init_argparse(parser)
    subparsers = parser.add_subparsers()

    p = subparsers.add_parser('checkout',
            help='Checkout all repos described by *.ini files, cloning and fetching as needed.',
            description='Checkout all repos described by *.ini files, cloning and fetching as needed. This will put the repos into "detached HEAD" state, just like git-submodules. Someday, we might add branch support.',
            #aliases=['co'],
            )
    p.set_defaults(func=cmds.checkout)

    p = subparsers.add_parser('prepare',
            help='Prepare to submit the current changes.',
            description='Prepare to submit the current changes, and `p4 edit` them. Work with intermediate *.ini.bak files. Users may run this command as often as they like. It is perfectly safe always. They must then run `p4 submit` themselves.',
            )
    p.add_argument('--no-verify',
            action='store_true',
            help='Do not perform the verify step.',
            )
    p.set_defaults(func=cmds.prepare)

    p = subparsers.add_parser('verify',
            help='Prove that the commit is actually available from a fresh checkout.',
            description='This will become faster when we have caching. Note that `prepare` can call this itself.',
            )
    p.set_defaults(func=cmds.verify)

    p = subparsers.add_parser('submit',
            help='DEPRECATED. Users should run `p4 submit` themselves.',
            description='DEPRECATED. `p4 submit` the prepared changes (*.ini.bak). Recommendation: Run with `-n` first.',
            )
    p.add_argument('-n', '--dry-run',
            action='store_true',
            help='Do not actually run any p4 commands.',
            )
    p.add_argument('-f', '--force',
            action='store_true',
            help='Submit all open files too. This helps you to coordinate changes, but it can also be a mistake.',
            )
    p.add_argument('-b', '--bug',
            default='999999',
            help='Bugzilla number.',
            )
    p.add_argument('-m', '--message',
            default='Updating SHA1s.',
            help='Brief message at top of submit description. Bug # and github links will be appended.',
            )
    p.set_defaults(func=cmds.submit)
    args = parser.parse_args(argv[1:])
    args.func(args)

main(sys.argv)
